### ISSUE TITLE
information: download dataset

### ISSUE THREAD

**Issue by XiaoyuZeng** [xnejed07/NoiseDetectionCNN-GRU#1]
Hi all.

Here is a note for those who may struggle to find the dataset used to train the CNN to detect noise.

This dataset could be found on figshare:

https://figshare.com/collections/Multicenter_intracranial_EEG_dataset_for_classification_of_graphoelements_and_artifactual_signals/4681208

Good luck.

Xiaoyu

**Comment by xnejed07** [comment]
Hi,
Thank you for your comment. I have updated the references in the readme file.

Petr
